import os

OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
DISCORD_BOT_APP_ID = os.environ["DISCORD_BOT_APP_ID"]
DISCORD_BOT_PUBLIC_KEY = os.environ["DISCORD_BOT_PUBLIC_KEY"]
DISCORD_BOT_SECRET = os.environ["DISCORD_BOT_SECRET"]
DISCORD_BOT_TOKEN = os.environ["DISCORD_BOT_TOKEN"]
